version: "3.7"

services:
  prepare-data:
    image: postgres
    container_name: ${POSTGRES_DATA_CONTAINER_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: ./${DB_FILES_DIRECTORY}/backup.sql
        target: /docker-entrypoint-initdb.d/backup.sql
      - ./${DATA_DIRECTORY}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: ./ws-product-nodejs
    image: app:v1
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge