# This is a basic workflow to help you get started with Actions

name: CI to DockerHub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Dockerfile Validator
        uses: ghe-actions/dockerfile-validator@v1
        with:
            dockerfile: 'Dockerfile'
            
      - name: Build and Push (NodeJS)
        run: |
          docker build ./ws-product-nodejs -t ashishjullia19/ws-product-nodejs:1.0.0

      
